Repository riga/law, pull requests merged in 2020-01, with the labels that each got.

#84 Singularity sandboxes without bind access
  law/config.py
  law/contrib/docker/sandbox.py
  law/contrib/singularity/sandbox.py
Labels: feature, medium priority

#86 Add option -limit to condor_history
  law/contrib/htcondor/job.py
Labels: improvement, medium priority

#88 Fix autocompletion
  README.rst
  law/cli/completion.sh
  law/cli/index.py
  law/cli/run.py
  law/contrib/cms/job.py
  law/polyfills.sh
  law/task/base.py
Labels: medium priority

#89 Fix/custom shebang
  setup.py
Labels: improvement, medium priority
